# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.12  # Certifique-se de que esta é a versão do Python que você está usando

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe  # Use com cautela, desativa algumas verificações de segurança
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    -   id: pyupgrade
        args:
        -   --py3-plus  # Converte código para Python 3+
        -   --keep-runtime-typing  # Mantém anotações de tipo em tempo de execução
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.2  # Verifique a versão mais recente
    hooks:
    -   id: ruff
        args:
        -   --fix  # Corrige automaticamente problemas de estilo
-   repo: https://github.com/psf/black
    rev: '24.4.2'  # Substitua pelo hash do commit que você escolheu
    hooks:
    -   id: black
        language_version: python3
